# Generated by Django 5.0.6 on 2026-06-10 23:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='项目标题')),
                ('category', models.CharField(choices=[('education', '教育助学'), ('medical', '医疗救助'), ('disaster', '灾害救援'), ('poverty', '扶贫济困'), ('environment', '环境保护'), ('animal', '动物保护'), ('elderly', '关爱老人'), ('children', '关爱儿童'), ('other', '其他公益')], default='other', max_length=50, verbose_name='项目分类')),
                ('description', models.TextField(verbose_name='项目简介')),
                ('detail_content', models.TextField(blank=True, null=True, verbose_name='详细内容')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='projects/covers/', verbose_name='封面图片')),
                ('target_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='目标金额（元）')),
                ('current_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='已筹金额（元）')),
                ('deadline', models.DateField(verbose_name='截止日期')),
                ('status', models.CharField(choices=[('pending', '待审核'), ('approved', '已通过'), ('rejected', '已拒绝'), ('funding', '募集中'), ('completed', '已完成')], default='pending', max_length=20, verbose_name='项目状态')),
                ('reject_reason', models.TextField(blank=True, null=True, verbose_name='拒绝原因')),
                ('audited_at', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('auditor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audited_projects', to=settings.AUTH_USER_MODEL, verbose_name='审核员')),
                ('initiator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL, verbose_name='项目发起方')),
            ],
            options={
                'verbose_name': '公益项目',
                'verbose_name_plural': '公益项目',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100, verbose_name='资金用途分类')),
                ('description', models.TextField(blank=True, null=True, verbose_name='用途说明')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='预算金额（元）')),
                ('quantity', models.IntegerField(default=1, verbose_name='数量')),
                ('unit', models.CharField(blank=True, max_length=20, null=True, verbose_name='单位')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='projects.project', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': '项目预算明细',
                'verbose_name_plural': '项目预算明细',
                'ordering': ['id'],
            },
        ),
    ]
