# Generated by Django 5.0.6 on 2026-06-11 13:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_donation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='execution_ratio_at_refund',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=6, verbose_name='退款时执行比例'),
        ),
        migrations.AddField(
            model_name='donation',
            name='platform_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='平台维护费（元）'),
        ),
        migrations.AddField(
            model_name='donation',
            name='refund_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='退款金额（元）'),
        ),
        migrations.AddField(
            model_name='donation',
            name='refund_transaction_id',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='退款交易流水号'),
        ),
        migrations.AddField(
            model_name='project',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='项目开始日期'),
        ),
        migrations.AddField(
            model_name='project',
            name='used_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='已使用金额（元）'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('pending', '待审核'), ('approved', '已通过'), ('rejected', '已拒绝'), ('funding', '募集中'), ('executing', '执行中'), ('completed', '已完成')], default='pending', max_length=20, verbose_name='项目状态'),
        ),
        migrations.CreateModel(
            name='RefundRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(max_length=1000, verbose_name='退款原因')),
                ('status', models.CharField(choices=[('pending', '待审核'), ('approved', '已通过'), ('rejected', '已拒绝')], default='pending', max_length=20, verbose_name='申请状态')),
                ('review_reason', models.TextField(blank=True, max_length=1000, null=True, verbose_name='审核意见')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='申请时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('donation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='refund_request', to='projects.donation', verbose_name='关联捐赠')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_refunds', to=settings.AUTH_USER_MODEL, verbose_name='审核员')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refund_requests', to=settings.AUTH_USER_MODEL, verbose_name='申请人')),
            ],
            options={
                'verbose_name': '退款申请',
                'verbose_name_plural': '退款申请',
                'ordering': ['-created_at'],
            },
        ),
    ]
