# Generated by Django 5.0.6 on 2026-06-11 14:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_donation_execution_ratio_at_refund_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expenditure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expenditure_type', models.CharField(choices=[('material', '物料采购'), ('cash', '现金发放'), ('service', '服务采购'), ('other', '其他支出')], default='other', max_length=20, verbose_name='支出类型')),
                ('title', models.CharField(max_length=200, verbose_name='支出标题')),
                ('description', models.TextField(verbose_name='支出说明')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='支出金额（元）')),
                ('expenditure_date', models.DateField(verbose_name='支出日期')),
                ('recipient', models.CharField(max_length=200, verbose_name='收款方/接收人')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operated_expenditures', to=settings.AUTH_USER_MODEL, verbose_name='经办人')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenditures', to='projects.project', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': '支出记录',
                'verbose_name_plural': '支出记录',
                'ordering': ['-expenditure_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExpenditureInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_no', models.CharField(blank=True, max_length=100, null=True, verbose_name='发票号码')),
                ('invoice_file', models.FileField(upload_to='invoices/', verbose_name='发票文件')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='发票金额（元）')),
                ('issued_date', models.DateField(blank=True, null=True, verbose_name='开票日期')),
                ('issuer', models.CharField(blank=True, max_length=200, null=True, verbose_name='开票方')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('expenditure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='projects.expenditure', verbose_name='所属支出')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_invoices', to=settings.AUTH_USER_MODEL, verbose_name='上传人')),
            ],
            options={
                'verbose_name': '支出发票',
                'verbose_name_plural': '支出发票',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DonationExpenditure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='分配金额（元）')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('allocated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allocated_donations', to=settings.AUTH_USER_MODEL, verbose_name='分配人')),
                ('donation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenditure_allocations', to='projects.donation', verbose_name='关联捐赠')),
                ('expenditure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donation_allocations', to='projects.expenditure', verbose_name='关联支出')),
            ],
            options={
                'verbose_name': '捐款支出分配',
                'verbose_name_plural': '捐款支出分配',
                'ordering': ['-created_at'],
                'unique_together': {('donation', 'expenditure')},
            },
        ),
    ]
