# Generated by Django 5.0.6 on 2026-06-12 00:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_expenditure_expenditureinvoice_donationexpenditure'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DonationCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_no', models.CharField(max_length=64, unique=True, verbose_name='证书编号')),
                ('certificate_type', models.CharField(choices=[('donation_threshold', '大额捐赠证书'), ('project_success', '项目筹款成功证书')], max_length=30, verbose_name='证书类型')),
                ('donation_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='捐赠金额（元）')),
                ('integrity_hash', models.CharField(max_length=128, verbose_name='完整性校验哈希')),
                ('issued_at', models.DateTimeField(auto_now_add=True, verbose_name='颁发时间')),
                ('donation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='projects.donation', verbose_name='关联捐赠')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='projects.project', verbose_name='所属项目')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donation_certificates', to=settings.AUTH_USER_MODEL, verbose_name='捐赠人')),
            ],
            options={
                'verbose_name': '捐赠证书',
                'verbose_name_plural': '捐赠证书',
                'ordering': ['-issued_at'],
            },
        ),
    ]
