# Generated by Django 5.0.6 on 2026-06-12 04:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_donationcertificate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('project_update', '项目进展'), ('donation_success', '捐赠成功'), ('project_completed', '项目完成'), ('system', '系统通知')], default='system', max_length=30, verbose_name='通知类型')),
                ('title', models.CharField(max_length=200, verbose_name='通知标题')),
                ('content', models.TextField(verbose_name='通知内容')),
                ('is_read', models.BooleanField(default=False, verbose_name='是否已读')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='阅读时间')),
                ('related_project_id', models.IntegerField(blank=True, null=True, verbose_name='关联项目ID')),
                ('related_update_id', models.IntegerField(blank=True, null=True, verbose_name='关联动态ID')),
                ('related_donation_id', models.IntegerField(blank=True, null=True, verbose_name='关联捐赠ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='接收用户')),
            ],
            options={
                'verbose_name': '通知',
                'verbose_name_plural': '通知',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='动态标题')),
                ('content', models.TextField(verbose_name='动态内容')),
                ('update_type', models.CharField(choices=[('text', '文字动态'), ('image', '图片动态'), ('video', '视频动态'), ('mixed', '混合动态')], default='text', max_length=20, verbose_name='动态类型')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('initiator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_updates', to=settings.AUTH_USER_MODEL, verbose_name='发布人')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='projects.project', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': '项目进展',
                'verbose_name_plural': '项目进展',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectUpdateImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='project_updates/images/', verbose_name='图片')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='图片描述')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('project_update', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='projects.projectupdate', verbose_name='所属动态')),
            ],
            options={
                'verbose_name': '进展图片',
                'verbose_name_plural': '进展图片',
                'ordering': ['sort_order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectUpdateVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='project_updates/videos/', verbose_name='视频文件')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='project_updates/video_covers/', verbose_name='视频封面')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='视频描述')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('project_update', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='projects.projectupdate', verbose_name='所属动态')),
            ],
            options={
                'verbose_name': '进展视频',
                'verbose_name_plural': '进展视频',
                'ordering': ['sort_order', 'created_at'],
            },
        ),
    ]
