# Generated by Django 5.0.6 on 2026-06-12 06:39

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_notification_projectupdate_projectupdateimage_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceiptRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_type', models.CharField(choices=[('electronic', '电子收据'), ('paper', '纸质收据'), ('paper_with_letter', '纸质收据（含感谢信）'), ('paper_with_gift', '纸质收据（含纪念品）')], max_length=30, verbose_name='收据类型')),
                ('badge_level_at_request', models.CharField(choices=[('bronze', '铜心勋章'), ('silver', '银心勋章'), ('gold', '金心勋章'), ('diamond', '钻石心勋章')], max_length=20, verbose_name='申请时勋章等级')),
                ('love_points_at_request', models.IntegerField(verbose_name='申请时爱心值')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='收据金额合计（元）')),
                ('recipient_name', models.CharField(max_length=100, verbose_name='收件人姓名')),
                ('recipient_address', models.CharField(max_length=500, verbose_name='收件地址')),
                ('recipient_phone', models.CharField(max_length=20, verbose_name='联系电话')),
                ('status', models.CharField(choices=[('pending', '待审核'), ('approved', '已通过'), ('rejected', '已拒绝'), ('mailed', '已邮寄')], default='pending', max_length=20, verbose_name='申请状态')),
                ('reject_reason', models.TextField(blank=True, null=True, verbose_name='拒绝原因')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('tracking_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='快递单号')),
                ('mailed_at', models.DateTimeField(blank=True, null=True, verbose_name='邮寄时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='申请时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('donations', models.ManyToManyField(related_name='receipt_requests', to='projects.donation', verbose_name='关联捐赠')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_receipt_requests', to=settings.AUTH_USER_MODEL, verbose_name='审核人')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipt_requests', to=settings.AUTH_USER_MODEL, verbose_name='申请人')),
            ],
            options={
                'verbose_name': '捐赠收据申请',
                'verbose_name_plural': '捐赠收据申请',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserHonorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_donation_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='累计捐赠金额（元）')),
                ('consecutive_donation_days', models.IntegerField(default=0, verbose_name='连续捐赠天数')),
                ('love_points', models.IntegerField(default=0, verbose_name='爱心值')),
                ('current_badge_level', models.CharField(blank=True, choices=[('bronze', '铜心勋章'), ('silver', '银心勋章'), ('gold', '金心勋章'), ('diamond', '钻石心勋章')], max_length=20, null=True, verbose_name='当前勋章等级')),
                ('last_donation_date', models.DateField(blank=True, null=True, verbose_name='最后捐赠日期')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='honor_profile', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户荣誉档案',
                'verbose_name_plural': '用户荣誉档案',
            },
        ),
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_level', models.CharField(choices=[('bronze', '铜心勋章'), ('silver', '银心勋章'), ('gold', '金心勋章'), ('diamond', '钻石心勋章')], max_length=20, verbose_name='勋章等级')),
                ('is_lit', models.BooleanField(default=True, verbose_name='是否点亮')),
                ('earned_at', models.DateTimeField(auto_now_add=True, verbose_name='获得时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户勋章',
                'verbose_name_plural': '用户勋章',
                'ordering': ['earned_at'],
                'unique_together': {('user', 'badge_level')},
            },
        ),
    ]
