from django.urls import path
from .views import (
    ProjectPublicListView,
    ProjectCreateView,
    ProjectDetailView,
    MyProjectListView,
    PendingProjectListView,
    ProjectAuditView,
    ProjectStartView,
    ProjectUpdateUsedAmountView,
    DonationCreateView,
    MyDonationListView,
    DonationDetailView,
    PaymentCallbackView,
    SimulatePaymentView,
    DonationRefundView,
    DonationRefundPreviewView,
    ProjectDonationListView,
    RefundRequestCreateView,
    MyRefundRequestListView,
    RefundRequestListView,
    RefundRequestReviewView,
    ExpenditureListView,
    ExpenditureCreateView,
    ExpenditureDetailView,
    ExpenditureInvoiceUploadView,
    DonationExpenditureAllocateView,
    DonationTrackingView,
    ProjectExpenditureSummaryView,
    AvailableDonationsForAllocationView,
    MyCertificateListView,
    CertificateDetailView,
    CertificateVerifyView,
    ProjectCertificateListView,
    ProjectUpdateListView,
    ProjectUpdateCreateView,
    ProjectUpdateDetailView,
    MyProjectUpdateListView,
    MySupportedProjectUpdatesView,
    NotificationListView,
    NotificationUnreadCountView,
    NotificationMarkReadView,
    NotificationDetailView,
    MyHonorProfileView,
    MyBadgesListView,
    BadgeDefinitionsView,
    RecalculateHonorView,
    ReceiptRequestCreateView,
    MyReceiptRequestListView,
    ReceiptRequestListView,
    ReceiptRequestDetailView,
    ReceiptRequestReviewView,
    ReceiptRequestMailingView,
    UserHonorProfileDetailView,
    UserBadgesListView
)

urlpatterns = [
    path('public/', ProjectPublicListView.as_view(), name='project_public_list'),
    path('create/', ProjectCreateView.as_view(), name='project_create'),
    path('my/', MyProjectListView.as_view(), name='project_my_list'),
    path('pending/', PendingProjectListView.as_view(), name='project_pending_list'),
    path('<int:pk>/', ProjectDetailView.as_view(), name='project_detail'),
    path('<int:pk>/audit/', ProjectAuditView.as_view(), name='project_audit'),
    path('<int:pk>/start/', ProjectStartView.as_view(), name='project_start'),
    path('<int:pk>/used-amount/', ProjectUpdateUsedAmountView.as_view(), name='project_update_used_amount'),
    path('<int:project_id>/donations/', ProjectDonationListView.as_view(), name='project_donation_list'),
    path('<int:project_id>/expenditures/', ExpenditureListView.as_view(), name='project_expenditure_list'),
    path('<int:pk>/expenditure-summary/', ProjectExpenditureSummaryView.as_view(), name='project_expenditure_summary'),

    path('donations/', DonationCreateView.as_view(), name='donation_create'),
    path('donations/my/', MyDonationListView.as_view(), name='donation_my_list'),
    path('donations/<int:pk>/', DonationDetailView.as_view(), name='donation_detail'),
    path('donations/<int:pk>/pay/', SimulatePaymentView.as_view(), name='donation_pay'),
    path('donations/<int:pk>/refund/', DonationRefundView.as_view(), name='donation_refund'),
    path('donations/<int:pk>/refund-preview/', DonationRefundPreviewView.as_view(), name='donation_refund_preview'),
    path('donations/<int:pk>/tracking/', DonationTrackingView.as_view(), name='donation_tracking'),
    path('donations/callback/', PaymentCallbackView.as_view(), name='donation_callback'),

    path('refunds/', RefundRequestCreateView.as_view(), name='refund_request_create'),
    path('refunds/my/', MyRefundRequestListView.as_view(), name='my_refund_request_list'),
    path('refunds/pending/', RefundRequestListView.as_view(), name='refund_request_list'),
    path('refunds/<int:pk>/review/', RefundRequestReviewView.as_view(), name='refund_request_review'),

    path('expenditures/', ExpenditureListView.as_view(), name='expenditure_list'),
    path('expenditures/create/', ExpenditureCreateView.as_view(), name='expenditure_create'),
    path('expenditures/<int:pk>/', ExpenditureDetailView.as_view(), name='expenditure_detail'),
    path('expenditures/<int:expenditure_id>/upload-invoice/', ExpenditureInvoiceUploadView.as_view(), name='expenditure_upload_invoice'),
    path('expenditures/<int:expenditure_id>/available-donations/', AvailableDonationsForAllocationView.as_view(), name='expenditure_available_donations'),

    path('allocations/', DonationExpenditureAllocateView.as_view(), name='allocation_create'),

    path('certificates/my/', MyCertificateListView.as_view(), name='certificate_my_list'),
    path('certificates/verify/', CertificateVerifyView.as_view(), name='certificate_verify'),
    path('certificates/<int:pk>/', CertificateDetailView.as_view(), name='certificate_detail'),
    path('<int:project_id>/certificates/', ProjectCertificateListView.as_view(), name='project_certificate_list'),

    path('updates/create/', ProjectUpdateCreateView.as_view(), name='project_update_create'),
    path('updates/my/', MyProjectUpdateListView.as_view(), name='my_project_update_list'),
    path('updates/my/<int:project_id>/', MyProjectUpdateListView.as_view(), name='my_project_updates_for_project'),
    path('updates/supported/', MySupportedProjectUpdatesView.as_view(), name='my_supported_project_updates'),
    path('updates/<int:pk>/', ProjectUpdateDetailView.as_view(), name='project_update_detail'),
    path('<int:project_id>/updates/', ProjectUpdateListView.as_view(), name='project_update_list'),

    path('notifications/', NotificationListView.as_view(), name='notification_list'),
    path('notifications/unread-count/', NotificationUnreadCountView.as_view(), name='notification_unread_count'),
    path('notifications/mark-read/', NotificationMarkReadView.as_view(), name='notification_mark_read'),
    path('notifications/<int:pk>/', NotificationDetailView.as_view(), name='notification_detail'),

    path('honor/my/', MyHonorProfileView.as_view(), name='my_honor_profile'),
    path('honor/my/badges/', MyBadgesListView.as_view(), name='my_badges_list'),
    path('honor/recalculate/', RecalculateHonorView.as_view(), name='honor_recalculate'),
    path('honor/badges/definitions/', BadgeDefinitionsView.as_view(), name='badge_definitions'),
    path('honor/profiles/<int:pk>/', UserHonorProfileDetailView.as_view(), name='user_honor_profile'),
    path('honor/users/<int:user_id>/badges/', UserBadgesListView.as_view(), name='user_badges_list'),

    path('receipts/', ReceiptRequestCreateView.as_view(), name='receipt_request_create'),
    path('receipts/my/', MyReceiptRequestListView.as_view(), name='my_receipt_request_list'),
    path('receipts/pending/', ReceiptRequestListView.as_view(), name='receipt_request_list'),
    path('receipts/<int:pk>/', ReceiptRequestDetailView.as_view(), name='receipt_request_detail'),
    path('receipts/<int:pk>/review/', ReceiptRequestReviewView.as_view(), name='receipt_request_review'),
    path('receipts/<int:pk>/mail/', ReceiptRequestMailingView.as_view(), name='receipt_request_mail'),
]
